#!/usr/bin/bash
box=$(dd if=/dev/random bs=32 count=1 | \
    pivtool box 9d | openssl enc -base64 | tr -d '\n')
echo "$box" | openssl enc -d -base64 | pivtool unbox | \
    zpool create -O encryption=on -O keyformat=raw \
    -O rfd77:box="$box" "$@"
